name: Pylint

on:
  push:
    branches:
      - aitlas-py-312-downstream-tasks
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Micromamba (Conda)
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: aitlas
        create-args: >-
          python=3.12
          gdal
          fiona
          rasterio
          -c conda-forge
        cache-environment: true

    - name: Install Pip Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analysing the code with pylint
      shell: bash -l {0}
      run: |
        pylint $(git ls-files '*.py')
